### ISSUE TITLE
Can you add torrentz2.is ?  torrentz2.eu has been permanently removed.

### ISSUE THREAD

**Issue by Necromantia000** [blha303/torrentz2-magnet#1]

**Comment by 3xploiton3** [comment]
yeah +1

**Comment by Krucifixa** [comment]
do it!

**Comment by blha303** [comment]
I don't use Torrentz anymore, or have an environment to develop chrome extensions. I would suggest forking the repository and publishing a new version to the chrome store.

**Comment by gilshallem** [comment]
I did it. the new extension is reviewed and will be available soon :)

**Comment by Krucifixa** [comment]
Awesome! Well done.

**Comment by gilshallem** [comment]
Here it is: https://chrome.google.com/webstore/detail/torrentz2-magnet-links/gfdagplpafaaplpkngcjbpkgeneapboc
Enjoy :)
